/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SW_PRESEL.h
**     Project     : Presel_ARM
**     Processor   : MK20DX128VLH5
**     Component   : BitsIO_LDD
**     Version     : Component 01.029, Driver 01.05, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-18, 11:29, # CodeGen: 77
**     Abstract    :
**         The HAL BitsIO component provides a low level API for unified
**         access to general purpose digital input/output 32 pins across
**         various device designs.
**
**         RTOS drivers using HAL BitsIO API are simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : SW_PRESEL
**          Port                                           : PTC
**          Pins                                           : 12
**            Pin0                                         : 
**              Pin                                        : ADC0_SE14/TSI0_CH13/PTC0/SPI0_PCS4/PDB0_EXTRG
**              Pin signal                                 : 
**            Pin1                                         : 
**              Pin                                        : ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/I2S0_TXD0
**              Pin signal                                 : 
**            Pin2                                         : 
**              Pin                                        : ADC0_SE4b/CMP1_IN0/TSI0_CH15/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/I2S0_TX_FS
**              Pin signal                                 : 
**            Pin3                                         : 
**              Pin                                        : CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUTa/I2S0_TX_BCLK
**              Pin signal                                 : 
**            Pin4                                         : 
**              Pin                                        : PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT
**              Pin signal                                 : 
**            Pin5                                         : 
**              Pin                                        : PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT
**              Pin signal                                 : 
**            Pin6                                         : 
**              Pin                                        : CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/I2S0_MCLK
**              Pin signal                                 : 
**            Pin7                                         : 
**              Pin                                        : CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS
**              Pin signal                                 : 
**            Pin8                                         : 
**              Pin                                        : CMP0_IN2/PTC8/I2S0_MCLK
**              Pin signal                                 : 
**            Pin9                                         : 
**              Pin                                        : CMP0_IN3/PTC9/I2S0_RX_BCLK
**              Pin signal                                 : 
**            Pin10                                        : 
**              Pin                                        : PTC10/I2S0_RX_FS
**              Pin signal                                 : 
**            Pin11                                        : 
**              Pin                                        : PTC11/LLWU_P11
**              Pin signal                                 : 
**          Direction                                      : Output
**          Initialization                                 : 
**            Init. direction                              : Output
**            Init. value                                  : 0
**            Auto initialization                          : yes
**          Safe mode                                      : no
**     Contents    :
**         Init   - LDD_TDeviceData* SW_PRESEL_Init(LDD_TUserData *UserDataPtr);
**         PutVal - void SW_PRESEL_PutVal(LDD_TDeviceData *DeviceDataPtr, uint32_t Val);
**
**     (c) 2012 by Freescale
** ###################################################################*/
/*!
** @file SW_PRESEL.h
** @version 01.05
** @brief
**         The HAL BitsIO component provides a low level API for unified
**         access to general purpose digital input/output 32 pins across
**         various device designs.
**
**         RTOS drivers using HAL BitsIO API are simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup SW_PRESEL_module SW_PRESEL module documentation
**  @{
*/         

#ifndef __SW_PRESEL_H
#define __SW_PRESEL_H

/* MODULE SW_PRESEL. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "IO_Map.h"
#include "GPIO_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 



/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define SW_PRESEL_PRPH_BASE_ADDRESS  0x400FF080U
  
/*! Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods. */
#define SW_PRESEL_DeviceData  ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_SW_PRESEL_ID))

/* Methods configuration constants - generated for all enabled component's methods */
#define SW_PRESEL_Init_METHOD_ENABLED  /*!< Init method of the component SW_PRESEL is enabled (generated) */
#define SW_PRESEL_PutVal_METHOD_ENABLED /*!< PutVal method of the component SW_PRESEL is enabled (generated) */

/* Definition of implementation constants */
#define SW_PRESEL_MODULE_BASE_ADDRESS PTC_BASE_PTR /*!< Name of macro used as the base address */
#define SW_PRESEL_PORTCONTROL_BASE_ADDRESS PORTC_BASE_PTR /*!< Name of macro used as the base address */
#define SW_PRESEL_PORT_MASK 0x0FFFU    /*!< Mask of the allocated pin from the port */
#define SW_PRESEL_PORT_VALID_VALUE_MASK 0x0FFF /*!< Mask of the allocated pins from the port as the first pin would be zero i.e. valid bits to be set in method PutVal */
#define SW_PRESEL_PIN_ALLOC_0_MASK 0x01 /*!< Mask of the first allocated pin from the port */
#define SW_PRESEL_PIN_ALLOC_0_INDEX 0U /*!< The index of the first allocated pin from the port */



/*
** ===================================================================
**     Method      :  SW_PRESEL_Init (component BitsIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* SW_PRESEL_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  SW_PRESEL_PutVal (component BitsIO_LDD)
*/
/*!
**     @brief
**         Specified value is passed to the Input/Output component. If
**         the direction is [input] saves the value to a memory or a
**         register, this value will be written to the pins after
**         switching to the output mode - using [SetDir(TRUE)] (see
**         [Safe mode] property for limitations). If the direction is
**         [output] it writes the value to the pins. (Method is
**         available only if the Direction = _[output]_ or
**         _[input/output]_).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Val             - Output value
*/
/* ===================================================================*/
void SW_PRESEL_PutVal(LDD_TDeviceData *DeviceDataPtr, uint32_t Val);

/* END SW_PRESEL. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __SW_PRESEL_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
